app/app.go, app/prefix.go, cmd/cronosd/cmd/root.go
- seal CapabilityKeeper
- seal sdk config
- call UpgradeKeeper.SetModuleVersionMap
- keep prefixes and coin type the same as ethermint
=> Problem: scaffolding is not up-to-date

.github/workflows/goreleaser.yml, Makefile
Solution:
- adopt the one in chain-main project
The new one is tested in 0.5.1 release.
=> Problem: gorelease workflow don't work

CHANGELOG.md, app/app.go, app/prefix.go, cmd/cronosd/cmd/root.go, go.mod, go.sum, gomod2nix.toml, integration_tests/helper.py, integration_tests/poetry.lock, integration_tests/pyproject.toml, integration_tests/shell.nix, nix/default.nix, nix/sources.json, nix/testenv.nix, scripts/devnet.yaml, scripts/set-delegate-keys.sh, x/cronos/keeper/hooks.go
Closes #9
- add gravity module to app
- verify address format at application level
- fix pystarport config files
- ~~replace keyring with patched version~~ extracted to separated PR
- build orchestrator in nix
- add a gravity hook implementation template in cronos module.
- add gravity custom gentx command
Testing will be done in another PR.
=> embed gravity bridge module

cmd/cronosd/cmd/root.go
Solution: make default keyring-backend as os 
for consistency
without this pr, adding default is `test`, and others are `os`,
so user cannot find the key correctly without specifying `keyring-backend` 
after applying this pr, when keyring-backend is not specified, default will be `os` , consistent
```
cronosd keys add mykey1 --algo "eth_secp256k1" --index 0 
cronosd keys list 
cronosd keys  show mykey1  
cronosd keys export mykey1   --unarmored-hex --unsafe
cronosd keys unsafe-import-eth-key my5   ....................  --home ./test
cronosd keys  list --home ./test
cronosd keys  show my5 --home ./test
```
=> Problem: key import,export not working correctly (fix #26)

.github/CODEOWNERS
Solution: created a team in https://github.com/orgs/crypto-org-chain/teams/cronos-dev/
and set up auto-assignment: https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-assignment-for-your-team
for 2 people in round-robin
=> Problem: PR review overhead

CHANGELOG.md, x/cronos/handler_test.go, x/cronos/keeper/evm.go, x/cronos/keeper/ibc.go, x/cronos/keeper/ibc_test.go, x/cronos/keeper/mock/ibckeeper_mock.go
=> Support ibc to crc20

.flake8, .github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/test.yml, Makefile, integration_tests/cosmoscli.py, integration_tests/shell.nix, nix/default.nix, nix/sources.nix
Closes: #79
- Run flake8 for python
- Run nixpkgs-fmt for nix
=> Problem: no python and nix format checker in CI

CHANGELOG.md, Makefile, app/prefix.go, cmd/cronosd/config/config.go, cmd/cronosd/config/prefix_mainnet.go, cmd/cronosd/config/prefix_testnet.go, integration_tests/test_gravity.py, integration_tests/utils.py
=> Change account prefix to crc

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
=> Bump ethermint v0.7.1

CHANGELOG.md, app/app.go, go.mod, go.sum, gomod2nix.toml, integration_tests/test_ibc.py
=> Release: v0.6.2

integration_tests/shell.nix, nix/default.nix, nix/sources.json
Closes: #250
Solution:
- update nixpkgs to release-21.11
- use go_1_17 as default go
- use builtin poetry2nix
=> Problem: go 1.17 is not used in nix build

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Solution:
- reject MsgEthereumTx wrapping tx without the extension option.
=> Problem: MsgEthereumTx wrapping tx without the extension option is not rejected

integration_tests/contracts/contracts/TestERC20Utility.sol, integration_tests/test_basic.py
backport: https://github.com/crypto-org-chain/cronos/pull/254
Solution:
- merge empty topics fix
- add integration tests to verify
=> Problem: empty topics in rpc response is not tested

CHANGELOG.md, app/app.go
Solution: Move the upgrade handler before sealing the app
=> Problem: app is sealed before upgrade handler is called

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, integration_tests/test_basic.py, nix/sources.json
Solution:
- update dependencies
=> Problem: final cosmos-sdk 0.45.0 is not used

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Solution: Bump gravity module version to latest main (d52551b27f65)
=> Problem: batchTxExecuted use wrong contract address in gravity bridge module

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Closes: #327
Solution:
- fix base fee check logic in ethermint.
=> Problem: 0.70-rc1 testnet does not support eth_call for blocks prior to upgrade

go.mod, go.sum, gomod2nix.toml
Closes: #281
Solution:
- use the fix in ethermint
=> Problem: eth_getLogs with large block range is slow and cause OOM

CHANGELOG.md, app/app.go, go.mod, go.sum, gomod2nix.toml, integration_tests/configs/cosmovisor.yaml, integration_tests/network.py, integration_tests/test_gravity.py, integration_tests/test_upgrade.py, nix/default.nix, nix/sources.json, x/cronos/types/interfaces.go
Solution:
- update ethermint/cosmos-sdk dependencies
- prepare a breaking upgrade on testnet
=> Problem: recent bug fixes are not included

LICENSE
Solution: fixed the license (cronos code didn't exist before 2021)
=> Problem: incorrect licensing information

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Solution:
- backport the feature to 0.45.x in cosmos-sdk
=> Problem: debug mode query result don't show panic info

README.md
Fix typo `quitck` to `quick` in README.
=> Problem: typo in README

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, integration_tests/conftest.py, integration_tests/network.py, integration_tests/poetry.lock, integration_tests/pyproject.toml, integration_tests/pytest.ini, integration_tests/test_basic.py, integration_tests/test_subscribe.py
Closes: #364
Solution:
- add cronos-ws provider to run exiting test cases on websocket endpoint
- add websocket subscription test cases
- update ethermint to fix websocket bugs
- port a log redirection feature
=> Problem: no integration test for websocket rpc endpoint

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
- [Quick fix for eth_feeHistory when reward is nil](https://github.com/tharsis/ethermint/pull/975)
- [Add buffer to eth_gasPrice response](https://github.com/tharsis/ethermint/pull/968)
- [Fix GasMeter reset in AnteHandler, aka. return correct gasWanted to tendermint](https://github.com/tharsis/ethermint/pull/964)
modified to only fix checkTx mode to avoid breaking consensus.
- [add returnValue message on tracing](https://github.com/tharsis/ethermint/pull/962)
=> Problem: recent bug fixes on ethermint not used

integration_tests/test_basic.py, integration_tests/test_upgrade.py
Closes: #379
Solution:
- add integration test to test tx inclusion logic when block gas limit exceeded.
=> Problem: tx inclusion logic when block gas limit exceeded is not tested

Makefile, app/app.go, go.mod, go.sum, gomod2nix.toml, integration_tests/test_basic.py, integration_tests/test_filters.py, integration_tests/utils.py
Closes: #403
Solution:
- fix in ethermint and update dependency
- add integration tests
=> Problem: ethermint recent fixes not included in main branch

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, integration_tests/configs/cosmovisor.yaml, integration_tests/test_upgrade.py
Solution:
- fix in ethermint and update the dependency
=> Problem: query legacy block failed after upgrade

CHANGELOG.md, default.nix, go.mod, go.sum, gomod2nix.toml
Solution:
- change the build tags in nix expression
- tag ethermint dependency to prepare the 0.7.0 release
=> Problem: nix build tags are different from goreleaser

CHANGELOG.md, app/app.go
Closes: #453
Solution:
- keep the latest testnet upgrade handler
=> Problem: testnet nodes can't switch to later 0.7.0 releases

CHANGELOG.md, cmd/cronosd/cmd/fix-unlucky-tx.go, cmd/cronosd/cmd/root.go, go.mod, go.sum, gomod2nix.toml, integration_tests/cosmoscli.py, integration_tests/test_replay_block.py, scripts/devnet.yaml, x/cronos/rpc/api.go
Closes: #455
- add fix-unlucky-tx command
- test in integration test
```
$ cronosd fix-unlucky-tx 1 106 --home data/cronos_777-1/node0
```
=> Problem: The unlucky transactions are not shown in json rpc

.github/workflows/codeql-analysis.yml
Solution:
- added a codeql pipeline with the Cosmos SDK bug-specific query pack
+ the general security and quality scan
+ a few handpicked experimental queries
=> Problem: missing scanning for common SDK issues (fixes #497)

docs/architecture/README.md, docs/architecture/adr-005.md
Solution: sketched out a draft for CCV usage where Cronos is the provider chain
for Gravity Bridge.
(note that the original issue considered Cronos could be a consumer chain
which may still be a valid option, but the complexity of transition may be too high.)
=> Problem: missing ADR draft for a transition to CCV (fixes #194)

CHANGELOG.md, cmd/cronosd/cmd/reindex-duplicated-tx.go, cmd/cronosd/cmd/root.go
Closes: #521
Solution:
- add reindex-duplicated-tx command
This command should work for the 0.6.x blocks too.
=> Problem: no command to patch the duplicated tx situation

default.nix
Solution:
- bump to `v0.8.0` to prepare gravity-bridge testnet binaries.
=> Problem: nix built binary version number is not bumped

.github/workflows/release.yml
Solution:
- specify permission explicitly
It defaults to read-only now, need explicit declaring.
=> Problem: release workflow don't permission to create release

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Solution:
- backport a non-breaking version of the fix in ethermint https://github.com/evmos/ethermint/pull/1176
=> Problem: eth tx hash not validated and some json-rpc return incorrect one

.github/workflows/test.yml
Solution:
- upload x86-macOS binary cache in CI
=> Problem: integration test nix-shell env building is slow

integration_tests/test_basic.py
=> Problem: no integration test case for fee calculation of reverted contract call tx.

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Solution:
- Due to bug https://github.com/evmos/ethermint/issues/1175, the first `ethereum_tx` event emitted in ante handler may be incorrect,
Althrough the root casue is fixed, but to avoid resync we can do a workaround in event parsing to override with the second one.
=> Problem: tx hash may be incorrect in event parsing

docs/gravity-bridge/systemd/setup-gorc-service.sh
Update gorc service curl target to crypto-org-chain/cronos repo
=> Problem: setup-gorc-service.sh points to wrong repo

CHANGELOG.md, x/cronos/middleware/conversion_middleware.go
The error is nil in case of AcknowledgementError
=> Problem: fix mistake on acknowledgement error in ibc middleware

CHANGELOG.md, app/app.go, default.nix, go.mod, go.sum, gomod2nix.toml, integration_tests/configs/cosmovisor.yaml, integration_tests/configs/upgrade-test-package.nix, integration_tests/test_upgrade.py, nix/default.nix, nix/sources.json
Solution:
- update ethermint to a fixed version
- add v0.7.0-hotfix upgrade plan
- bump version number
=> Problem: selfdestruct could affect other contracts with same bytecode

CHANGELOG.md, README.md, app/app.go, go.mod, go.sum, gomod2nix.toml, integration_tests/configs/enable-indexer.jsonnet, integration_tests/conftest.py, scripts/devnet.yaml, third_party/proto/ethermint/types/v1/indexer.proto, x/cronos/rpc/api.go
Solution:
- enable and test the custom tx indexer feature
=> Problem: customer tx indexer feature is not enabled

CHANGELOG.md, app/app.go, app/genesis.go, app/state.go, app/test_helpers.go, cmd/cronosd/cmd/root.go, integration_tests/configs/disable_auto_deployment.jsonnet, integration_tests/configs/genesis_token_mapping.jsonnet, integration_tests/poetry.lock, scripts/cronos-experimental-devnet.yaml, scripts/devnet.yaml
Solution:
- Use different module managers according to --unsafe-experimental flag
=> Problem: init/validate-genesis cmd include gravity module by default

.github/workflows/sims.yml
=> Problem: the sims test triggered by pull request comments does not report final results

cmd/cronosd/cmd/root.go
Solution: add missing flag and baseapp.SetIAVLCacheSize
=> Problem: (fix #684)missing baseapp function to configure iavl-cache-size

.github/workflows/build.yml, .github/workflows/linkchecker.yml, .github/workflows/lint.yml, .github/workflows/test.yml, integration_tests/test_gravity.py, integration_tests/test_ibc.py
Solution:
- fix wildcards according the plugin's doc
- reformat python
=> Problem: file changes detection in workflow is problematic

CHANGELOG.md, cmd/cronosd/cmd/root.go
Closes: #712
Solution:
- Integrate the option introduced in cosmos-sdk
=> Problem: new iavl indexes migration is slow and not optional

CHANGELOG.md, app/app.go, client/flags.go, cmd/cronosd/cmd/root.go, integration_tests/configs/default.jsonnet, integration_tests/network.py, integration_tests/poetry.lock, integration_tests/pyproject.toml, integration_tests/test_streamer.py, nix/testenv.nix
Solution:
- integration the basic file streamer
=> Problem: state streamers are not integrated (backport #702)

CHANGELOG.md, cmd/cronosd/cmd/root.go
Closes: https://github.com/crypto-org-chain/cronos/issues/712
Solution:
- Integrate the option introduced in cosmos-sdk
=> Problem: new iavl indexes migration is slow and not optional (backport: #714)

CHANGELOG.md, app/upgrades.go, go.mod, go.sum, gomod2nix.toml, integration_tests/configs/upgrade-test-package-gravity.nix, integration_tests/cosmoscli.py, integration_tests/test_upgrade_gravity.py
=> Problem: no upgrade handler for v0.8.0-gravity-alpha2

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Thanks: @mmsqe 
Solution:
- update dependencies to include the fix
=> Problem: evm execute result is non-deterministic with concurrent grpc query

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Solution:
- cherry-pick solution from ethermint, thanks @mmsqe
it's tested in ethermint integration test.
=> Problem: different result from eth_getProof comparing with Ethereum

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml
Solution:
- configure access-token
- update the action plugins
=> Problem: nix exceeds github rate limit occasionally in CI

CHANGELOG.md, integration_tests/test_gravity.py, x/cronos/keeper/evmhandlers/cancel_send_to_evm_chain.go, x/cronos/keeper/evmhandlers_test.go
Solution: check that only the event emitted from contract address can cancel the token it manages
=> Problem: anyone can call the cancellation function

CHANGELOG.md
=> Problem: final v1.0.0 is not released

CHANGELOG.md, cmd/cronosd/cmd/root.go
=> Problem: manual prune cmd is not included (backport #781)

CHANGELOG.md, app/upgrades.go, go.mod, go.sum, gomod2nix.toml
Solution:
- update ibc-go to v5.2.0.
- do another coordinated upgrade on testnet3, plan name: `v1.0.0-testnet3-2`.
=> Problem: discontinued ibc-go version

Makefile, cmd/cronosd/cmd/open_db.go, cmd/cronosd/cmd/open_db_rocksdb.go, cmd/cronosd/cmd/root.go, default.nix, flake.lock, flake.nix, go.mod, go.sum, gomod2nix.toml, nix/default.nix, nix/rocksdb.nix, nix/sources.json
Solution:
- update related dependencies to allow custom rocksdb options.
- using rocksdb v7, closes #759 
- tune rocksdb options.
During the versiondb migration experiments, I found the default rocksdb settings are multiple times slower than the one I experimented, because I've tuned options and did a full compaction on the db before, but after I keep the node running with the normal binary for a while, suddenly my script's performance drop significantly, and the sst files are all rewritten by compaction process.
I suspect the main difference is sst file sizes, and probably filter and compression types as well, so I plan to tune the rocksdb options for default binary first, then try the versiondb migration script again, to see if it can get back to the old speed.
- Tool: `sst_dump …
=> Problem: production rocksdb configuration is not optimal

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Solution:
- setup correctly in ethermint
=> Problem: prometheus metrics is lost

.github/workflows/codeql-analysis.yml
Solution: updated the query paths to the new repository
=> Problem: codeql-go is deprecated

.github/workflows/codeql-analysis.yml
Solution: updated the query paths to the new repository
backport of https://github.com/crypto-org-chain/cronos/pull/820
=> Problem: codeql-go is deprecated (#820)

.github/workflows/test.yml
for more info: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes
=> Problem: default timeout for integration_tests is too long

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/lint.yml, .github/workflows/sims.yml, Makefile, flake.lock, flake.nix, go.mod, integration_tests/poetry.lock, integration_tests/pyproject.toml, integration_tests/test_gravity.py, nix/default.nix, nix/hermes.nix, nix/sources.json, nix/testenv.nix, versiondb/go.mod
Solution:
- update nixpksg to release-22.11
- manually patch golang version
=> Problem: recent golang compiler 1.19.6 is not used

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml
Solution:
- pin to nix 2.13 to workaround compability issue with 2.14
=> Problem: nix-action fail in CI

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml
Solution:
- pin to nix 2.13 to workaround compability issue with 2.14
=> Problem: nix-action fail in CI (backport #899)

CHANGELOG.md, cmd/cronosd/cmd/versiondb.go, cmd/cronosd/opendb/opendb_rocksdb.go, go.mod, go.sum, gomod2nix.toml, versiondb/go.mod, versiondb/go.sum
Closes: #902 
Solution:
- enable it on new db, but don't override existing db
- another implication is, user can manually modify the OPTIONS file to tune those options that's not set by app
=> Problem: dynamic-level-bytes is not enabled for restored application.db

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Solution:
- fix in ethermint and update dependency
=> Problem: dynamic fee extension is problematic

default.nix, flake.nix, nix/default.nix, nix/rocksdb.nix
Solution:
- it's possible to support static build on linux with a few tweaks.
=> Problem: static build on linux fails (backport: #925)

CHANGELOG.md, memiavl/export.go, memiavl/snapshot.go, memiavl/snapshot_test.go
=> Problem: export API not supported in memiavl

app/bench_test.go, app/test_helpers.go
Solution:
- add the first benchmark for tx delivery (typical erc20 transfers)
```
$ go test -run=^$ -bench=BenchmarkERC20Transfer -benchmem ./app
goos: darwin
goarch: amd64
pkg: github.com/crypto-org-chain/cronos/v2/app
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
BenchmarkERC20Transfer/memdb-12         	       1	1316400164 ns/op	277784600 B/op	 4731271 allocs/op
BenchmarkERC20Transfer/leveldb-12       	       1	1385148085 ns/op	278984336 B/op	 4729347 allocs/op
PASS
ok  	github.com/crypto-org-chain/cronos/v2/app	5.249s
```
- it takes around 1.3s to execute a block with 1000 erc20 transfer txs
- profile shows ante handler spend a little bit more than msg execution
- goleveldb result is very close to memdb.
- ethereum sender recovery is a hotspot, another one seems to be `GetParams`. …
=> Problem: tx delivery performance is not benchmarked

.github/workflows/test.yml, flake.lock, nix/sources.json
Solution:
- update nixpkgs to recent master
- re-enable coverage report for integration tests
=> Problem: go 1.20.2 is not used

memiavl/import.go, memiavl/snapshot.go, memiavl/snapshot_test.go
Solution:
- implement Import function to convert state-sync snapshot to memiavl snapshot
=> Problem: memiavl import API not implemented

CHANGELOG.md, app/app.go, integration_tests/cosmoscli.py, integration_tests/test_ibc_update_client.py
Solution: add missing client route for ibc
=> Problem: no handler exists for proposal type when update-client

CHANGELOG.md, scripts/release.sh
Solution:
- use static-linking in release script
=> Problem: released linux binaries don't use static linking (backport #949)

CHANGELOG.md, versiondb/client/convert_to_sst.go, versiondb/client/verify.go
Solution:
- skip the stores who are added after the target version
---------
=> Problem: changeset verify command return wrong app-hash on old blocks (backport #985)

app/app.go, memiavl/import.go, memiavl/snapshot.go, memiavl/snapshot_test.go
Solution:
- override cms before the other options, so the custom cms is always used
- fix importer close
- write metadata file when import
=> Problem: memiavl fail to run state sync

memiavl/db.go
Closes: #977
Solution:
- add mutex to `memiavl.DB`.
The assumptions to concurrency:
- The methods on `DB` are protected by a mutex
- each call of `LoadVersion` loads a separate instance, in query scenarios, it should be immutable, the cache stores will handle the temporary writes.
- the `DB` for the state machine will handle writes through the `Commit` call, this method is the sole entry point for tree modifications, and there's no concurrency internally (the background snapshot rewrite is handled separately), so we don't need locks in the `Tree`.
=> Problem: memiavl rootmulti integration is not thread-safe to use

app/app.go, integration_tests/configs/default.jsonnet, memiavl/db.go, memiavl/db_test.go, store/rootmulti/store.go
Solution:
- introduce `store.async-wal` option to write wal asynchronously
- rename the `memiavl` flag to `store.memiavl`.
In the block replaying test, it reduce the sync time from 2m to 1m10s, 40% reduction.
=> Problem: wal write is heavy in block replaying

default.nix, flake.lock, flake.nix, nix/build_overlay.nix, nix/default.nix, nix/sources.json
* Problem: go 1.20.3 is not used
Solution:
- update nixpkgs and go src
* add missing file
* fix rustc
---------
=> Problem: go 1.20.3 is not used (backport #1012)

CHANGELOG.md, integration_tests/test_ibc.py, x/cronos/keeper/evmhandlers/send_cro_to_ibc.go, x/cronos/keeper/evmhandlers/send_to_ibc.go, x/cronos/keeper/evmhandlers/send_to_ibc_v2.go, x/cronos/keeper/ibc.go, x/cronos/keeper/ibc_test.go, x/cronos/keeper/msg_server.go
=> Problem: channel id is not supported for send-to-ibc event 

memiavl/benchmark_test.go, memiavl/export.go, memiavl/import.go, memiavl/iterator.go, memiavl/layout_little_endian.go, memiavl/layout_native.go, memiavl/mem_node.go, memiavl/mmap.go, memiavl/node.go, memiavl/persisted_node.go, memiavl/snapshot.go
Closes: #1016 
`20%` improvement in `RandomGet` benchmark.
```
$ go test -run=^$ -bench="RandomGet/memiavl-disk" -benchmem ./ -count=4 -tags nativebyteorder
```
```
$ benchstat /tmp/before.txt /tmp/after.txt
goos: darwin
goarch: amd64
pkg: github.com/crypto-org-chain/cronos/memiavl
cpu: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
│ /tmp/before.txt │           /tmp/after.txt            │
│     sec/op      │    sec/op     vs base               │
RandomGet/memiavl-disk-12      175.8n ± ∞ ¹   138.2n ± ∞ ¹  -21.37% (p=0.029 n=4)
¹ need >= 6 samples for confidence interval at level 0.95
│ /tmp/before.txt │         /tmp/after.txt         │
│      B/op       │    B/op      vs base           │
RandomGet/memiavl-disk-12       0.000 ± ∞ ¹   0.000 ± ∞ ¹  ~ (p=1.000 n=4) ²
¹ need >= 6 samples for …
```
=> Problem: memiavl leaf node separation optimization is not implemented

CHANGELOG.md, app/config/config.go, app/config/toml.go, app/memiavl.go, memiavl/db.go, memiavl/snapshot_test.go, store/rootmulti/store.go
Solution:
- change the bool option to int
=> Problem: async commit queue size not configurable

integration_tests/test_ibc.py
Solution:
- dynamically calculate the expected ibc denom, becuase the contract address rely on current account nonce.
=> Problem: ibc integration test can't run standalone

CHANGELOG.md, app/config/config.go, app/config/toml.go, app/memiavl.go, go.mod, integration_tests/configs/default.jsonnet, memiavl/benchmark_test.go, memiavl/db.go, memiavl/db_test.go, memiavl/go.mod, memiavl/iterator_test.go, memiavl/multitree.go, memiavl/proof_test.go, memiavl/snapshot_test.go, memiavl/tree.go, memiavl/tree_test.go, store/rootmulti/store.go, versiondb/client/restore_app_db.go, versiondb/client/verify.go
Solution:
- ignore the inter-block cache silently
- roll it's own cache in memiavl trees
=> Problem: memiavl zero-copy don't work with inter-block cache

CHANGELOG.md, flake.lock, go.mod, go.sum, gomod2nix.toml
* update ibc-go to v5.2.1
* add change doc
=> Problem: fixes in ibc-go v5.2.1 are not included (backport #1038)

CHANGELOG.md, Makefile, default.nix, memiavl/layout_native.go
Solution:
- check native byte order in init, panic if native byte order is not little endian.
- build binary with nativebyteorder by default, big endian machine need to build it's own binary without the nativebyteorder tag.
=> Problem: nativebyteorder is not safe to use

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml
Solution:
- update to v22, see https://github.com/cachix/install-nix-action/pull/184
=> Problem: install-nix-action fails with recent macos update

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml
Solution:
- update to v22, see https://github.com/cachix/install-nix-action/pull/184
=> Problem: install-nix-action fails with recent macos update (backport #1068)

CHANGELOG.md, integration_tests/test_mempool.py, memiavl/export.go, memiavl/import.go, store/rootmulti/store.go
Solution:
- add defers and close functions
=> Problem: memiavl has resource leaks

CHANGELOG.md, app/app.go, memiavl/db.go, memiavl/db_test.go, memiavl/tree.go, store/rootmulti/store.go
if there are empty values, because protobuf decodes empty value as `nil`.
Solution:
- make sure empty value is represented as empty slice instead of nil in set operation.
=> Problem: memiavl result is different when replaying write-ahead-log

CHANGELOG.md, integration_tests/configs/rollback.jsonnet, memiavl/db.go, memiavl/export.go, memiavl/import.go, store/rootmulti/store.go
=> Problem: memiavl don't support rollback

CHANGELOG.md, memiavl/README.md, memiavl/db.go, memiavl/db_test.go
Closes: https://github.com/crypto-org-chain/cronos/issues/1095
=> Problem: memiavl leave tmp directories behind

.github/workflows/build.yml, .github/workflows/lint.yml, CHANGELOG.md, integration_tests/test_gravity.py, integration_tests/test_ibc.py, x/cronos/keeper/gravity_hooks.go, x/cronos/keeper/keeper.go
for more info, see https://github.com/cosmos/cosmos-sdk/pull/13063/files
=> Problem: duplicate cache events are emitted

CHANGELOG.md, memiavl/db.go, memiavl/db_test.go
Solution:
- wait for async commit to finish to make sure catching up to latest state.
=> Problem: memiavl snapshot rewrite could rollback state

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, integration_tests/cosmoscli.py, integration_tests/test_upgrade.py, memiavl/go.mod, x/cronos/client/cli/tx.go
=> Problem: feeibc, evm, feemarket and gravity gensis migrate is broken

nix/rocksdb.nix
Solution:
- fix the fixup script
=> Problem: rocksdb tools has wrong rpath

CHANGELOG.md, integration_tests/test_basic.py, memiavl/import.go, store/rootmulti/store.go
Solution:
- grab the file lock before restoration starts, to prevent multiple concurrent restorations.
- close the db before doing the restoration.
- reproduce the issue in integration test.
=> Problem: memiavl restore fail to reopen the db

integration_tests/cosmoscli.py, integration_tests/test_upgrade.py, integration_tests/utils.py
Closes: https://github.com/crypto-org-chain/cronos/issues/1138
=> Problem: start with exported genesis is not tested

CHANGELOG.md, memiavl/db_test.go, memiavl/mem_node.go, memiavl/node.go, memiavl/persisted_node.go, memiavl/tree.go
Solution:
- clone the byte slices when nesserary
=> Problem: memiavl's root hash is not safe to retain in commit info

CHANGELOG.md, store/cachemulti/store.go, store/rootmulti/store.go
Solution:
- add a wrapper that supports io.Closer
Impact:
- this PR only adds a Closer method to it, but not call it, for example, sdk grpc query service will not call it, unless patched.
- versiondb nodes handle grpc queries without memiavl, so no problem there.
- for other use cases that use memiavl's `CacheMultiStoreWithVersion` method should call the `Close()` method explicitly.
- ideally we should patch sdk itself to add Close method, it's relevant to existing iavl as well.
=> Problem: memiavl db in CacheMultiStoreWithVersion not closed

app/app.go, go.mod, go.sum, gomod2nix.toml, x/cronos/keeper/precompiles/interface.go, x/cronos/keeper/precompiles/relayer.go, x/cronos/keeper/precompiles/utils.go
=> Problem: event converter don't have to be global

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, memiavl/db.go, memiavl/export.go, memiavl/go.mod, memiavl/go.sum, memiavl/mmap.go, memiavl/multitree.go, store/go.mod, store/go.sum, store/setup.go, versiondb/go.mod, versiondb/go.sum
=> Problem: memiavl background snapshot writing don't limit concurrency level 

integration_tests/contracts/contracts/TestICA.sol, integration_tests/test_ica_precompile.py
=> Problem: invalid ica msg is not tested

app/app.go, integration_tests/configs/ibc.jsonnet, integration_tests/test_ica_precompile.py, x/cronos/keeper/precompiles/bank.go, x/cronos/keeper/precompiles/ica.go, x/cronos/keeper/precompiles/relayer.go
Using some base line value for estimation, may need adjustment in the future
Open for suggestions. Keeping this open as it is important to have this fixed before an official release.
=> Problem: precompiles required-gas need adjustments

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, integration_tests/configs/cosmovisor.jsonnet, integration_tests/configs/default.jsonnet, integration_tests/cosmoscli.py, integration_tests/test_upgrade.py
=> Problem: miss keypair of SendEnabled to restore legacy param set before migration

client/docs/config.json, client/docs/swagger-ui/swagger.yaml
=> Problem: ica swagger is not updated

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, memiavl/db.go, memiavl/db_test.go, memiavl/import.go, x/cronos/keeper/mock/ibckeeper_mock.go
=> Problem: ethermint is not updated

client/docs/config.json, client/docs/swagger-ui/swagger.yaml
rm host params, add icaauth query params
=> Problem: icaauth swagger is not updated

CHANGELOG.md, memiavl/import.go
* Problem: memiavl restore not fast enough
Solution:
- increase channel buffer size to improve parallisation
it reduce restore time by 44% when testing with testnet, thanks @yzang2019 for sharing the finding.
* fix unit test
---------
=> Problem: memiavl restore not fast enough (backport #1241)

app/app.go
=> Problem: black list addresses are not logged

app/app.go
This PR implements the proposed changes from #1333, addressing the issue with logging levels. Initially, I intended to use the warn log level, but it appears that the `Warn()` method lacks implementation in "github.com/tendermint/tendermint/libs/log". Therefore, I opted for the error log level to ensure visibility, considering the importance of the logs in question.
To minimize operator confusion, it could be beneficial to further clarify the log messages to indicate that this level of logging is intentional and chosen for its visibility before merging.
Based on [release/v1.0.x](https://github.com/crypto-org-chain/cronos/tree/release/v1.0.x) since it is the origin of the change in #1328 
- ~~[ ] Have you included tests for any non-trivial functionality?~~
- ~~[ ] If you added any …
=> Feature Request: Enhance blacklist logging visibility (Issue #1333)

CHANGELOG.md, app/app.go, app/versiondb.go, app/versiondb_placeholder.go, go.mod, store/go.mod, store/rootmulti/store.go, versiondb/go.mod, versiondb/multistore.go
Closes: #1226
Solution:
- share the mem store instance with the main store
* fix
* verify the fix
* fix mem store
* Update versiondb/multistore.go
---------
=> Problem: versiondb multistore can't query mem store state (backport #1230)

integration_tests/cosmoscli.py, integration_tests/test_basic.py, integration_tests/utils.py
- add a integration test case for demonstration
=> Problem: no doc for feemarket param gov proposal

memiavl/go.mod, memiavl/go.sum, store/go.mod, store/go.sum, versiondb/go.mod, versiondb/go.sum
due to golang/protobuf version mismatch
=> Problem: failed to load package descriptor

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, integration_tests/configs/cosmovisor.jsonnet, integration_tests/configs/upgrade-test-package.nix, integration_tests/cosmoscli.py, integration_tests/test_upgrade.py, integration_tests/utils.py, x/cronos/rpc/api.go
=> Problem: no parsed log from old event

.github/workflows/release.yml
Because macos-latest becomes M1 mac now.
Solution:
- update runner
=> Problem: release workflow don't build x86 mac (backport #1423)

app/app.go, app/block_address.go, integration_tests/configs/long_timeout_commit.jsonnet, integration_tests/test_mempool.py
=> Problem: mempool logic should be kept

CHANGELOG.md, app/app.go, app/proposal.go
Solution:
- keep the default prepare proposal logics: check the block size limit and gas limit
=> Problem: default prepare proposal logic is missing

CHANGELOG.md, x/cronos/keeper/precompiles/relayer.go
For more [info](https://github.com/cosmos/ibc-go/blob/v7.3.2/modules/apps/transfer/keeper/relay.go#L196), denom can't be [converted](https://github.com/crypto-org-chain/cronos/blob/release/v1.3.x/x/cronos/middleware/conversion_middleware.go#L110) in middleware.
=> Problem: require gas in RecvPacket is inaccurate when ReceiverChainIsSource (backport #1458) 

CHANGELOG.md, integration_tests/configs/upgrade-test-package.nix, integration_tests/test_basic.py, integration_tests/test_upgrade.py, versiondb/tsrocksdb/store.go
=> Problem: memory leak in versiondb (backport: #1491)

CHANGELOG.md, versiondb/tsrocksdb/iterator.go
=> Problem: redundant copy in check validate (back port: #1498)

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
=> Problem: cometbft is not up to date

.github/workflows/test.yml, CHANGELOG.md, cmd/cronosd/opendb/opendb_rocksdb.go
- Suspect large `application.db`
- try cache index/filters
Update CHANGELOG.md
=> Problem: memory leak in archive node (backport #1526)

.github/workflows/build.yml, .github/workflows/lint.yml, CHANGELOG.md, Makefile, app/app.go, app/block_address.go, x/cronos/types/messages.go, x/cronos/types/messages_test.go
=> Problem: sender check for MsgStoreBlockList is not in CheckTx (backport #1613)

CHANGELOG.md, versiondb/go.mod, versiondb/multistore.go, versiondb/store.go
=> Problem: versiondb NewKVStore don't accept string as store name

.github/workflows/lint.yml, Makefile, contracts/shell.nix, default.nix, flake.nix, integration_tests/configs/broken-cronosd.nix, integration_tests/configs/upgrade-test-package.nix, integration_tests/shell.nix, nix/build_overlay.nix, nix/bundle-win-exe.nix, nix/cosmovisor.nix, nix/cronos-matrix.nix, nix/dapptools-overlay.nix, nix/default.nix, nix/gen-binding-shell.nix, nix/go-ethereum.nix, nix/hermes.nix, nix/rocksdb.nix, nix/scripts.nix, nix/sources.nix, nix/testenv.nix, nix/testground-image.nix, testground/benchmark/flake.nix, testground/benchmark/overlay.nix
Solution:
- switch to nixfmt-rfc-style
=> Problem: nixpkgs-fmt is deprecated (backport: #1677)

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
=> Problem: ethermint bug fixes not included

CHANGELOG.md, default.nix, go.mod, go.sum, gomod2nix.toml
Upgade cosmos sdk to patch a bug
=> [Problem] cosmos sdk does not include latest bugfixes

.github/workflows/build.yml, .github/workflows/container.yml, .github/workflows/gosec.yml, .github/workflows/linkchecker.yml, .github/workflows/lint.yml, .github/workflows/proto.yml, .github/workflows/release.yml, .github/workflows/sims.yml, .github/workflows/test.yml, CHANGELOG.md
=> Problem: changelog is outdated
