.github/workflows/build.yml, .github/workflows/goreleaser.yml, .github/workflows/linkchecker.yml, .github/workflows/lint.yml, .golangci.yml, .goreleaser.yml, Makefile, app/app.go, app/encoding.go, cmd/cronosd/cmd/root.go, docs/docs.go, go.mod, go.sum, x/cronos/client/cli/tx.go, x/cronos/handler.go, x/cronos/module.go, x/cronos/types/codec.go, x/cronos/types/genesis.go
Closes #4
- build/lint/test/release
- also updated dependencies
=> Add github action for CI

.github/CODEOWNERS
Solution: add devashish and JayT106
=> Problem: code owners are not complete

go.mod, go.sum, gomod2nix.toml
Solution:
- replace keyring dependency with patched one
=> Problem: patched keyring is not used

CHANGELOG.md, default.nix, go.mod, go.sum, gomod2nix.toml
Solution:
- update to main branch of ethermint
- update changelogs
=> Problem: recent ethermint bug fixes are not included

RELEASE_CHANGELOG.md
=> v0.5.1 Release Notes

app/app.go
Solution:
- add capability module to `SetOrderBeginBlockers`
=> Problem: capability error when setup ibc channel

cmd/cronosd/cmd/genaccounts.go, go.mod
Solution:
- adopt genaccount command from ethermint
=> Problem: genesis accounts are not EthAccount

.github/workflows/sims.yml, Makefile, app/app.go, app/config.go, app/export.go, app/sim_test.go, app/state.go, app/test_helpers.go, app/types.go, app/utils.go
Closes #20
- add simulation test and run in ci
- will run when merged to main branch, or triggered manually
- fix export issue
=> Run simulation tests in CI

Makefile
=> Problem: missing install in Makefile (fix #39)

.github/workflows/build.yml
Closes #42
- run gomod2nix on CI
- check working directory is clean
=> check gomod2nix up to date on CI

integration_tests/test_gravity.py, integration_tests/utils.py
Closes #48
Solution:
- use better method to wait for message relaying
=> Problem: gravity bridge integration test fails occasionally

go.mod, go.sum
Closes: #71
Solution:
- Change repo to the one under org.
=> Problem: personal gravity-bridge fork is used

integration_tests/cosmoscli.py, integration_tests/poetry.lock, integration_tests/pyproject.toml, integration_tests/test_gravity.py, integration_tests/utils.py
Closes: #73
Solution:
- generate orchestrator keys on the fly
=> Problem: It's not tested that orchestrator using different key from the validator

.goreleaser.yml, CHANGELOG.md, RELEASE_CHANGELOG.md
=> Release v0.5.4-testnet

go.mod, go.sum, gomod2nix.toml
Closes: #97
Solution:
- replace iavl to v0.17.1
- also update ethermint since previous PR merged
=> Problem: node crash under concurrent query

app/app.go, integration_tests/contracts/contracts/TestERC20Utility.sol, integration_tests/cosmoscli.py, integration_tests/test_gravity.py, integration_tests/utils.py, proto/cronos/cronos.proto, scripts/cronos-devnet.yaml, x/cronos/client/cli/tx.go, x/cronos/client/proposal_handler.go, x/cronos/client/rest/rest.go, x/cronos/keeper/keeper.go, x/cronos/proposal_handler.go, x/cronos/types/codec.go, x/cronos/types/cronos.pb.go, x/cronos/types/proposal.go
Closes: #46
- Add token mapping change gov proposal handler
- gov token mapping integration test
=> Problem: no governance managed native to contract mapping

go.mod, go.sum, gomod2nix.toml, integration_tests/test_gravity.py, nix/default.nix, nix/sources.json
Closes: #91
Solution:
- update both to the consolidated cronos branch
=> Problem: different Gravity Bridge versions used in Nix integration tests and in Go build

x/cronos/module.go
Closes: #106
Solution:
- register them
=> Problem: cronos query api not registered in grpc gateway

docs/gravity-bridge-setup-guide.md, integration_tests/cosmoscli.py, integration_tests/test_gravity.py
Closes: #52
Solution:
- document the steps of gravity bridge setup
- change signer_set_txs to latest_signer_set_tx for simpler code in integration test
=> Problem: no local gravity bridge setup instructions

.github/workflows/sims-protected.yml, .github/workflows/sims.yml
Closes #112
Solution:
- make duplicated sims workflow that runs on unprotected environment
=> Problem: sims test don't run automatically on main branch

Makefile
=> Problem: add clean task in Makefile

README.md
Update invalid link in READMD.md
=> Problem: update readme link

integration_tests/contracts/contracts/Gravity.sol, integration_tests/utils.py
Closes: #126
Solution:
- add `sendToCronos`, where the type of recipient parameter is address
=> Problem: sendToCosmos's recipient parameter type is confusing

x/cronos/keeper/hooks.go, x/cronos/types/events.go, x/cronos/types/interfaces.go
Solution: Emit events in AfterSendToCosmosEvent hook
This PR is related to https://github.com/crypto-org-chain/gravity-bridge/pull/12
=> Problem: Events are insufficient for monitoring gravity transfer

.goreleaser.yml, Makefile
Closes: #135
Solution:
- main branch goreleaser build testnet binaries by default
- remove the need for RELEASE_CHANGELOGS.md, could modify on Github manually
=> Problem: not able to release from main branch directly

CHANGELOG.md, default.nix
=> release v0.5.5-testnet

README.md, docs/integration-test.md
This pull request is adding an integration test document illustrating the required steps the user should do.
Replace #121 
The related issue is #82
=> Add document - integration Test

docs/api/json-rpc/endpoints.md, docs/api/json-rpc/events.md, docs/api/json-rpc/namespaces.md, docs/api/json-rpc/server.md
Since docs moved from ethermint to evmos, it would make sense to replicate the minimum necessary docs
=> Problem: missing json-rpc docs

x/cronos/types/types_test.go
=> Problem: types_test.go does not include tests with realistic parameters

x/cronos/keeper/gravity_hooks.go
Solution: (Fix #163) Update module name in event
=> Problem: After SendToCosmos event module is incorrect

docs/architecture/adr-002.md
=> Problem: missing decision record for a custom fork of ibc-go

default.nix
=> Problem: Confusing ver number default.nix (#199)

integration_tests/cosmoscli.py, integration_tests/poetry.lock, integration_tests/test_basic.py, integration_tests/utils.py, nix/sources.json
Close #6
This pull request relies on the following two pull requests, please help review them and merge them first.
https://github.com/crypto-com/pystarport/pull/34
https://github.com/crypto-com/pystarport/pull/32
=> Problem: no integration test for state sync #6 #201

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/test.yml, integration_tests/test_basic.py, integration_tests/utils.py, nix/default.nix
Closes: #206
Solution:
- enable experimental-features
=> Problem: CI fails with nix 2.4

README.md
Signed-off-by: Landan Hu <landan@crypto.com>
Solution: add the above 3 missing info.
=> Problem: Missing build status, test-cov and discord info on repo front page

SECURITY.md
Solution: updated the security policy to point to Immunefi
=> Problem: incorrect bug bounty program

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
=> Release: v0.6.3

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
=> Problem: tharsis#786 is consensus breaking

CHANGELOG.md
=> Release: v0.6.4

integration_tests/utils.py, scripts/.env, scripts/start-geth
=> Problem: The address and the private keys should be derived from the mnemonics in integration test

.goreleaser.yml
Closes: #258
Solution:
- set draft option to `true`
- don't do dry-run in CI
I've verified in this test repo: https://github.com/yihuang/test-goreleaser/actions
=> Problem: CI don't create draft release for review

integration_tests/contracts/contracts/TestRevert.sol, integration_tests/test_basic.py, integration_tests/utils.py
=> Problem: no integration test for transaction index

cmd/cronosd/cmd/root.go
=> Problem: Redundant vesting subcommands

integration_tests/contracts/contracts/TestMessageCall.sol, integration_tests/contracts/contracts/TestRevert.sol, integration_tests/test_basic.py, integration_tests/utils.py
Closes: #132
Solution:
- stress test contract which do as much message calls as possible
- test contract state reverted on exception
=> Problem: contract message calls are not tested

.github/workflows/goreleaser.yml
Closes: #273
Solution:
- remove unnecessary steps
It's tested in this repo: https://github.com/yihuang/test-goreleaser/blob/master/.github/workflows/goreleaser.yml
=> Problem: goreleaser workflow do dry-run unnecessarily

integration_tests/test_basic.py, integration_tests/test_exported_genesis.py, integration_tests/test_gravity.py, integration_tests/test_ibc.py, integration_tests/utils.py
=> Problem: the contract paths in integration tests are hard to maintain

integration_tests/contracts/contracts/TestSuicide.sol, integration_tests/test_basic.py, integration_tests/utils.py
Closes: #285
Solution:
test that:
- within the tx, after the contract suicided, the code still exists.
- after the tx, the code no longer exist.
BTW, this test case don't pass for current ethermint, it's only fixed in statedb-refactor branch.
=> Problem: contract suicide is not tested

docs/architecture/README.md, docs/architecture/adr-003.md
=> Problem: no ADR document for feemarket module

.goreleaser.yml
Solution: add a suffix for testnet build in .goreleaser
=> Problem: incorrect version is displayed for testnet binary

go.mod, go.sum
Problem: 
This issue is first spotted in `chain-indexing`, https://github.com/crypto-com/chain-indexing/issues/661.
`github.com/enigmampc/btcutil` is vulnerable now and we need to remove it from our dependencies.
Solution:
Replace it with `github.com/scrtlabs/btcutil`.
=> Problem: dependency `github.com/enigmampc/btcutil` is vulnerable

integration_tests/configs/cosmovisor.yaml, integration_tests/configs/upgrade-test-package.nix, integration_tests/network.py, integration_tests/shell.nix, integration_tests/test_upgrade.py, integration_tests/utils.py, nix/default.nix, nix/sources.json
Closes #247 
- add basic upgrade integration test with cosmovisor
=> Problem: no integration test for v0.7.0 upgrade

integration_tests/cosmoscli.py, integration_tests/test_basic.py, integration_tests/utils.py, scripts/cronos-devnet.yaml, scripts/devnet.yaml
Closes: #305
- add batch tx integration test
=> Problem: batched eth tx is not tested

CHANGELOG.md
Solution:
- add changelogs from dependencies upgrades.
- merge 0.6.5 changelog.
=> Problem: missing some important changelogs

contracts/src/ModuleCRC20.sol
update the comment on module address.
=> Problem: comment in ModuleCRC20.sol is out of date

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Solution:
- update the dependency.
[cosmos-sdk v0.45.1 release notes](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.45.1).
This may fix the larger memory usage issue we observe in the upgraded testnet.
=> Problem: cosmos-sdk v0.45.1 not used

CHANGELOG.md, Makefile, README.md, cmd/cronosd/cmd/root.go, default.nix, go.mod, go.sum, gomod2nix.toml, integration_tests/shell.nix, nix/default.nix, nix/sources.json
Solution:
* add RocksDB build
* update gomod2nix.toml
* fix gomod2nix
* add db_backend parameter to nix build
=> Problem: rocksdb not supportted in 0.6.x (backport #298)

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Closes: #207
Solution:
- backport the fix to 0.6.x
=> Problem: subscription deadlock fix is not backported to 0.6.x

docs/integration-test.md
Solution:
- update integration test doc
=> Problem: integration test doc don't mention contract compilation

CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, docs/architecture/README.md, x/cronos/spec/01_concepts.md
Solution:
Update descriptions and fix typos so the content aligns with the Cronos context.
=> Problem: out-of-date content that doesn't align with Cronos context

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Solution:
- backport ethermint#878
=> Problem: GetBlock rpc api report wrong gasUsed

.github/workflows/release.yml, .goreleaser.yml, Makefile
=> Problem: rocksdb release tar file naming not aligned with existing naming

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Closes: #362
Solution:
- fix a panic in subscription with non-eth tx
=> Problem: websocket connection closed occationally on mainnet

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Closes: #371
Solution:
- backport the fix to ethermint and update dependency.
=> Problem: transaction count don't match in different json-rpc apis

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Solution:
- backport the fix in ethermint fork and update dependency
=> Problem: tracing returnValue fix is not backported

integration_tests/cosmoscli.py, integration_tests/test_basic.py, integration_tests/test_ibc.py, integration_tests/utils.py
Closes: #366
Solution:
- modify current ibc test to cover basecro transfer
=> Problem: no integration test for send_cro_to_crypto_org

docs/architecture/README.md, docs/architecture/adr-003.md, docs/architecture/adr-004.md
=> Problem: Missing ADR for token conversion logic

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Solution:
- revert the problamatic commits on top of cosmos-sdk 0.44.x release branch
=> Problem: there are subtle consensus breaking changes

app/app.go, go.mod, go.sum, gomod2nix.toml
Solution:
- update ibc-go to current v2.2.x
- add testnet upgrade handler
=> Problem: ibc use arbitrary error message as the acknowledgement

CHANGELOG.md, Makefile, app/app.go, go.mod, go.sum, gomod2nix.toml, integration_tests/test_basic.py, integration_tests/test_filters.py, integration_tests/utils.py
Solution:
- backport the fixes and update ethermint dependencies
- add an configurable upper bound to gasWanted to prevent DoS attack
- two small fixes on json-rpc
=> Problem: ethermint recent fixes not included

.github/workflows/release.yml, .goreleaser.yml, flake.lock, flake.nix
Closes: #406
Solution:
- use the new nix bundle solution
- pass tag_name to action-gh-release to upload artifact to existing release
- use draft release again, seems to work in test
=> Problem: rocksdb release flow failed

.github/workflows/lint.yml
Solution:
- upgrade golinter action
=> Problem: go linter fail in CI

integration_tests/cosmoscli.py, integration_tests/network.py, integration_tests/test_basic.py, integration_tests/test_exported_genesis.py, integration_tests/test_upgrade.py, integration_tests/utils.py
Prevent `ResourceWarning: unclosed` file in tests.
Solution: ensure file descriptors are automatically closed using appropriate functions.
=> Problem: resource warnings in integration tests

app/app.go, go.mod, go.sum, gomod2nix.toml, integration_tests/cosmoscli.py, integration_tests/test_basic.py, integration_tests/utils.py, scripts/cronos-devnet.yaml, scripts/devnet.yaml, x/cronos/rpc/api.go, x/cronos/rpc/utils.go
Closes: #431
Solution:
- add extension api: cronos_getTransactionReceiptsByBlock to fetch receipts in batch.
Example:
- add `cronos` namespace to `json-rpc.api` config.
- run:
```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"cronos_getTransactionReceiptsByBlock","params":["0x10"],"id":1}' -H "Content-Type: application/json" $ETH_RPC_URL
```
=> Problem: get tx receipt api is too slow for indexing service

app/app.go, integration_tests/configs/low_block_gas_limit.yaml, integration_tests/test_replay_block.py, proto/cronos/query.proto, scripts/protoc-swagger-gen.sh, x/cronos/keeper/evm_hooks_test.go, x/cronos/keeper/evm_log_handlers_test.go, x/cronos/keeper/grpc_query.go, x/cronos/keeper/ibc_hooks_test.go, x/cronos/keeper/ibc_test.go, x/cronos/keeper/keeper.go, x/cronos/keeper/params_test.go, x/cronos/rpc/api.go, x/cronos/types/interfaces.go, x/cronos/types/query.go, x/cronos/types/query.pb.go
Closes: #437
Solution:
- Support fetch tx receipts by replaying block
> wait for https://github.com/crypto-org-chain/cronos/pull/432 to get merged first.
New API:
```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"cronos_replayBlock","params":["0x18"],"id":1}' -H "Content-Type: application/json" $ETH_RPC_URL
```
=> Problem: can't get back tx result of false-failed tx

app/app.go, integration_tests/configs/upgrade-test-package.nix, integration_tests/test_upgrade.py
Closes: #333
Solution:
- set correct parameters in upgrade handler
=> Problem: feemarket parameters are not correct after upgrade

.github/workflows/lint.yml, app/app.go, cmd/cronosd/config/prefix_mainnet.go, go.mod, go.sum, gomod2nix.toml, integration_tests/configs/low_block_gas_limit.yaml, integration_tests/contracts/contracts/TestMessageCall.sol, integration_tests/test_replay_block.py, proto/cronos/query.proto, scripts/protoc-swagger-gen.sh, x/cronos/keeper/evm_hooks_test.go, x/cronos/keeper/evm_log_handlers_test.go, x/cronos/keeper/grpc_query.go, x/cronos/keeper/ibc_hooks_test.go, x/cronos/keeper/ibc_test.go, x/cronos/keeper/keeper.go, x/cronos/keeper/params_test.go, x/cronos/rpc/api.go, x/cronos/types/interfaces.go, x/cronos/types/query.go, x/cronos/types/query.pb.go
Closes: #437
Solution:
- Support fetch tx receipts by replaying block
- add integration test
* fix PR suggestions
=> Problem: can't get back tx result of false-failed tx (backport #438)

.github/workflows/release.yml, .goreleaser.yml, Makefile, default.nix, flake.lock, flake.nix
Closes: #444
Solution:
- build relocatable rocksdb binary using nix
- add six rocksdb binaries to CI release flow:
- rocksdb-x86_64-Darwin[-testnet]
- rocksdb-x86_64-Linux[-testnet]
- rocksdb-arm64-Linux[-testnet]
test run: https://github.com/yihuang/cronos/releases/tag/v0.0.28-test
- `cronosd-tarball`
- `cronosd-testnet-tarball`
- `cronosd-goleveldb-tarball`
- `cronosd-testnet-goleveldb-tarball`
And run on different platform/arch to get more binaries.
```
$ nix build github:yihuang/cronos/bundle-rocksdb#cronosd-exe
$ find ./result/
./result/
./result/exe
./result/exe/cronosd
./result/bin
./result/bin/cronosd
./result/lib
./result/lib/libc-2.33.so
./result/lib/libbz2.so.1
./result/lib/libzstd.so.1.5.2
./result/lib/liblz4.so.1
./result/lib/libstdc++.so.6.0.28 …
```
=> Problem: no relocatable rocksdb binary in CI

integration_tests/configs/cosmovisor.yaml, integration_tests/configs/disable_auto_deployment.yaml, integration_tests/configs/genesis_token_mapping.yaml, integration_tests/configs/low_block_gas_limit.yaml, scripts/cronos-devnet.yaml, scripts/cronos-experimental-devnet.yaml
Closes: #456
Solution:
- Add option `index-events = [ "ethereum_tx.ethereumTxHash" ]` in app.toml for integration_tests to verify it's enough for the json-rpc to work.
=> Problem: minimal tx event indexing is not tested

.github/workflows/release.yml
=> Problem: no windows rocksdb binary built automatically (fix #452)

.github/workflows/release.yml
move to release.yml
clarify build option
=> Problem: no windows rocksdb binary built automatically (fix #452) (backport #460)

cmd/cronosd/cmd/fix-unlucky-tx.go
=> Problem: fix-unlucky-tx command runs too slow

CHANGELOG.md, cmd/cronosd/cmd/fix-unlucky-tx.go
Solution: support null tx indexer
=> Problem: fix-unlucky-tx can't work with null indexer

.github/workflows/release.yml, .goreleaser.yml, default.nix, flake.lock, flake.nix
Closes: #464
Solution:
- build linux and x86_64-darwin goleveldb release binaries using nix too.
- upload checksums for nix built binaries.
=> Problem: released goleveldb binaries has external libc dependencies

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/proto.yml, .github/workflows/test.yml
Solution:
- exclude some workflows according to code changes.
[github action doc on paths](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore)
=> Problem: heavy CI workflows run too much

CHANGELOG.md, flake.lock, flake.nix, integration_tests/shell.nix, nix/sources.json
Closes: #473
Solution:
- `enableJemalloc = true`
- update rocksdb-src to v6.29.5
Although it didn't show significant improvement in production nodes, but switch to `jemalloc` should have positive effects.
Also upgrade rocksdb source to the latest `v6.x.x` version.
=> Problem: rocksdb version don't use optimal memory allocator

.github/workflows/release.yml, .goreleaser.yml, default.nix, flake.lock, flake.nix
backport #476
Problem: released goleveldb binaries has external libc dependencies
Closes: #464
Solution:
- build linux and x86_64 darwin goleveldb binaries using nix bundle-exe.
- upload sha256 checksums for nix built binaries.
- don't dereference symbolic link in tarball to avoid duplicated files.
- use netgo for better portability
=> Problem: released goleveldb binaries has external libc dependencies (backport #476)

flake.lock, flake.nix, gomod2nix.toml, nix/sources.json
Solution:
- fix the bug in upstream: https://github.com/tweag/gomod2nix/pull/38
- update dependency
- regenerate gomod2nix.toml
=> Problem: gomod2nix.toml need manual adjustment

CHANGELOG.md, flake.lock, flake.nix, integration_tests/shell.nix, nix/sources.json
Closes: #473
Solution:
- `enableJemalloc = true`
- update rocksdb-src to v6.29.5
=> Problem: rocksdb version don't use optimal memory allocator (backport #489)

.github/workflows/build.yml, gomod2nix.toml
Solution:
- use a simpler solution
verified: https://github.com/crypto-org-chain/cronos/runs/6649208587?check_suite_focus=true
=> Problem: dirty check github action plugin don't work anymore

.github/workflows/build.yml
Solution:
- use a simpler solution
=> Problem: dirty check github action plugin don't work anymore (backport #519)

integration_tests/utils.py
Solution:
- double the default timeout
=> Problem: gravity bridge test timeout occasionally

integration_tests/utils.py
Solution:
- double the default timeout
=> Problem: gravity bridge test timeout occationally (backport #528)

.github/workflows/linkchecker.yml, docs/api/json-rpc/events.md, docs/architecture/adr-template.md
Solution:
- fix deadlink
- fix deadlink check workflow
=> Problem: there's deadlink in docs

integration_tests/test_eip1559.py
Solution:
- add test for eth_gasPrice is base fee of the block just produced + eth_maxPriorityFeePerGas
- add test for eth_gasPrice should be bigger than or equal to the base fee of the next block
=> Problem: test eth_gasPrice RPC method

default.nix, flake.lock, flake.nix, gomod2nix.toml, nix/default.nix, nix/sources.json
=> Problem: recent improvements in gomod2nix are not used (backport #518)

cmd/cronosd/cmd/fix-unlucky-tx.go, integration_tests/cosmoscli.py
=> Problem: 0.7.x fix-unlucky-tx command does not include concurrency and null indexer

cmd/cronosd/cmd/reindex-duplicated-tx.go
=> Problem: fix reindex duplicated command fail when indexed tx is nil

integration_tests/configs/long_timeout_commit.yaml, integration_tests/test_mempool.py
add transaction and contract tx mempool behave test
=> Problem: mempool behaviors are not tested (fix #307)

integration_tests/contracts/contracts/CronosGravity.sol, integration_tests/contracts/contracts/Gravity.sol, integration_tests/poetry.lock, integration_tests/pyproject.toml, integration_tests/test_gravity.py, integration_tests/utils.py
=> Problem: gravity contract in integration test is not the CronosGravity.sol

docs/architecture/README.md, docs/architecture/adr-006.md
=> Problem: no decision record for crc21 standard and crc20 token migration

docs/api/json-rpc/endpoints.md, docs/api/json-rpc/events.md, docs/api/json-rpc/server.md, docs/architecture/README.md, docs/architecture/adr-007.md
=> Problem: no decision record for generic event format for evm-hook

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
=> Problem: gravity module does not contains latest patches (v2.0.1)

docs/gravity-bridge/pioneer11-orchestrator-relayer-deployment-guide.md, docs/gravity-bridge/pioneer11-relayer-only-deployment-guide.md, docs/gravity-bridge/systemd/gorc.service.template
- Update tx-set-delegate keys flag in docs
- Add reference section with deployed contracts
- Fix RELAYER_API_URL environment variable inside systemd service
=> Update Pioneer11 Deployment Guide

integration_tests/test_gravity.py
Closes: https://github.com/crypto-org-chain/cronos/issues/553
=> Problem: cancel gravity transfer integration test fail accationally

.github/workflows/release.yml
Solution:
- specify permission explicitly
=> Problem: release workflow don't have permission to create release (forward port: #569)

default.nix, go.mod, go.sum, gomod2nix.toml, integration_tests/configs/pruned-node.yaml, integration_tests/test_pruned_node.py, x/cronos/rpc/api.go
Solution:
- Make basic json-rpc apis works on pruned nodes
- Test with integration tests
=> Problem: json-rpc failed on pruned nodes (backport #550)

.github/workflows/build.yml, .github/workflows/lint.yml, Makefile, default.nix, flake.lock, flake.nix, go.mod, gomod2nix.toml, integration_tests/poetry.lock, nix/default.nix, nix/go_1_18_overlay.nix, nix/sources.json, nix/testenv.nix
=> Problem: latest cosmos-sdk commits require upgrading go1.17 to go1.18

.golangci.yml, app/app.go, app/export.go, app/sim_test.go, app/state.go, app/test_helpers.go, app/utils.go, cmd/cronosd/cmd/root.go, x/cronos/genesis_test.go, x/cronos/handler.go, x/cronos/handler_test.go, x/cronos/keeper/evm_log_handlers.go, x/cronos/keeper/ibc_test.go, x/cronos/keeper/keeper.go, x/cronos/keeper/keeper_test.go, x/cronos/keeper/mock/ibckeeper_mock.go, x/cronos/keeper/msg_server.go, x/cronos/keeper/params_test.go, x/cronos/middleware/conversion_middleware.go, x/cronos/module.go, x/cronos/types/codec.go, x/cronos/types/genesis_test.go, x/cronos/types/params.go, x/cronos/types/tracer.go, x/cronos/types/types_test.go, x/icactl/module_ibc.go, x/icactl/types/params.go
Solution:
- copy the one from ethermint
- fix linter suggestions
=> Problem: .golangci.yml is too old

default.nix
Solution:
- bump to `v0.7.1`
Signed-off-by: yihuang <huang@crypto.com>
=> Problem: version of nix binaries is not bumped

CHANGELOG.md, cmd/cronosd/cmd/fix-unlucky-tx.go, cmd/cronosd/cmd/fix-unlucky-tx_test.go, integration_tests/test_replay_block.py
Closes: https://github.com/crypto-org-chain/cronos/issues/576
=> Problem: patch-unlucky-tx don't handle duplicated tx correctly

.gitignore, CHANGELOG.md, cmd/cronosd/cmd/fix-unlucky-tx.go, cmd/cronosd/cmd/fix-unlucky-tx_test.go, integration_tests/test_replay_block.py
=> Problem: fasten unlucky tx patch

CHANGELOG.md, cmd/cronosd/cmd/fix-unlucky-tx.go
Solution:
- always recompute tx hash
same issue as: https://github.com/crypto-org-chain/cronos/pull/584
=> Problem: patch cmd may use incorrect tx hash

cmd/cronosd/cmd/fix-unlucky-tx.go, cmd/cronosd/cmd/fix-unlucky-tx_test.go
=> Problem: exported block result is not patched

.github/workflows/sims.yml
=> Problem: `/rumsim` failed because pr workflow does not have write permissions to comment

.github/workflows/test.yml
Solution:
- add `nix-store -r` to it
=> Problem: upload-cache job don't do actual build

.github/workflows/sims.yml
Solution:
- provide commit sha with `/runsim` when it is from third party pr
=> Problem: sims.yml doesn't enforce fix commit for third party pr

CHANGELOG.md
- Update CHANGELOG
- release v0.7.1 after merged
=> Problem: v0.7.1 is not released

.github/workflows/sims.yml
=> Problem: sims.yml has syntax error

integration_tests/cosmoscli.py, integration_tests/test_vesting.py
=> Problem: create_vesting_account is not tested

integration_tests/test_basic.py, integration_tests/test_filters.py, integration_tests/test_mempool.py, integration_tests/utils.py
=> Problem: mempool test is not stable

.github/workflows/sims.yml
close: #659 
change `checkUserMember` to `checkMember` in the member job
=> Problem: sims.yml uses the wrong step id checkUserMember instead of checkMember

app/upgrades.go
backport [a485dffc48975acbb792945f76b52ae6ab2ce543](https://github.com/crypto-org-chain/cronos/commit/a485dffc48975acbb792945f76b52ae6ab2ce543)
=> Problem: v0.8.0-cronos-alpha1 upgrade height not set correctly 

.github/workflows/release.yml, .goreleaser.yml
Closes: #668
Solution:
- keep the rocksdb version only
- build testnet verson
- upload checksums
=> Problem: windows rocksdb build job don't upload checksum

go.mod, go.sum, gomod2nix.toml
Solution:
- update dependencies
=> Problem: cosmos-sdk v0.45.8 is not used in 0.8.x

app/app.go, integration_tests/test_upgrade.py
Solution:
- do some basic operations after upgraded.
=> Problem: upgrade test don't reveal some upgrade issues

docs/api/json-rpc/events.md, docs/architecture/adr-005.md
Solution: Updated with working links
Signed-off-by: Calvin Lau <38898718+calvinaco@users.noreply.github.com>
=> Problem: Some links in doc are broken

.github/workflows/release.yml, scripts/codesign_macos.sh
Closes: #510
Soluton:
- sign the x86-64 mac binaries in the release workflow
=> Problem: mac binaries are not signed with apple developer certificates

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, integration_tests/test_basic.py
Solution:
- clear the `From` field when building tx.
=> Problem: eth_sendTransaction api don't work

.github/workflows/sims.yml
=> Problem: Sims workflow don’t follow security best practice

.github/workflows/build.yml, .github/workflows/linkchecker.yml, .github/workflows/lint.yml, .github/workflows/test.yml
Solution:
- fix wildcards according the plugin's doc
=> Problem: file changes detection in workflow is problematic (backport #703)

README.md
=> update README file with gomod2nix info

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, integration_tests/test_gravity.py, nix/default.nix, nix/sources.json
Include latest bugfix related to attestation processing and double spend prevention
=> Problem: gravity bridge is not up to date

integration_tests/cosmoscli.py, integration_tests/test_gravity.py, integration_tests/utils.py
close https://github.com/crypto-org-chain/cronos/issues/726
=> Problem: no integration test for multiple attestation processing (gravity bridge)

integration_tests/cosmoscli.py, integration_tests/test_basic.py, integration_tests/test_gravity.py
=> Problem: no test for new gov proposal format

default.nix
Solution:
- bump version number
=> Problem: binary version is not bumped to v1.0.0

nix/hermes.nix, nix/sources.json
=> Problem: latest hermes is not used in integration tests

.github/workflows/build.yml, .github/workflows/linkchecker.yml, .github/workflows/lint.yml, .github/workflows/proto.yml, .github/workflows/release.yml, .github/workflows/sims.yml, .github/workflows/test.yml
Solution:
- update set-output to new syntax
- ugprade some dependencies
=> Problem: workflow contains deprecated syntax

go.mod, go.sum, gomod2nix.toml
Solution:
- revert the changes in ethermint
=> Problem: gas used is not backward compatible

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test.yml
Solution:
- configure access-token
- update the action plugins
=> Problem: nix exceeds github rate limit occationally in CI (backport #766)

CHANGELOG.md, app/upgrades.go
Solution:
- set the london hardfork number to zero for testnet3 network
=> Problem: london hardfork number failed validation

.github/workflows/semgrep.yml
=> Problem: semgrep results are not uploaded

CHANGELOG.md, cmd/cronosd/cmd/root.go
=> Problem: manual prune cmd is not included

go.mod, go.sum, gomod2nix.toml, integration_tests/configs/disable_auto_deployment.jsonnet, integration_tests/contracts/contracts/CosmosToken.sol, integration_tests/contracts/contracts/Gravity.sol, integration_tests/contracts/contracts/ICosmosToken.sol, integration_tests/network.py, integration_tests/test_gravity.py, nix/default.nix, nix/sources.json
=> Problem: gravity module is not up to date

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/lint.yml, .github/workflows/sims.yml, Makefile, app/export.go, app/state.go, go.mod, nix/default.nix, x/cronos/client/cli/tx.go, x/cronos/keeper/evm_hooks_test.go, x/cronos/keeper/evm_test.go, x/cronos/keeper/evmhandlers_test.go, x/cronos/keeper/keeper_test.go, x/cronos/keeper/params_test.go
fix golangci-lint base on PR #804
=> problem: fix  golangci-lint

flake.nix
Solution:
- expose rocksdb through flake file, user can install ldb/sst_dump through cronos flake, for example:
```
nix profile install github:crypto-org-chain/cronos/release/v1.0.x#rocksdb.tools
```
=> Problem: not easy to install compactible rocksdb tools

.github/workflows/lint.yml, .golangci.yml, app/export.go, app/state.go, cmd/cronosd/cmd/open_db_rocksdb.go, flake.lock, flake.nix, nix/default.nix, nix/sources.json, x/cronos/client/cli/tx.go, x/cronos/keeper/evm_hooks_test.go, x/cronos/keeper/evm_test.go, x/cronos/keeper/evmhandlers_test.go, x/cronos/keeper/keeper_test.go, x/cronos/keeper/params_test.go, x/cronos/simulation/genesis_test.go, x/cronos/types/events.go
* fix nix-shell
* update golint config from cosmos-sdk
* upgrade golint action
* fix lint
Co-authored-by: HuangYi <huang@crypto.com>
=> problem: fix golangci-lint (backport #805)

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, integration_tests/configs/cosmovisor.jsonnet, integration_tests/configs/cosmovisor_gravity.jsonnet, integration_tests/configs/default.jsonnet
Solution:
- update cosmos-sdk to support lazy loading
- support new config option `iavl-lazy-loading: true`.
* enable lazy loading in integration test
Signed-off-by: yihuang <huang@crypto.com>
* fix test config
* Update integration_tests/configs/cosmovisor.jsonnet
Co-authored-by: mmsqe <tqd0800210105@gmail.com>
Signed-off-by: yihuang <huang@crypto.com>
* update to release branch
* bump to v0.46.9-rc.0
---------
Signed-off-by: yihuang <huang@crypto.com>
Co-authored-by: mmsqe <tqd0800210105@gmail.com>
=> Problem: node startup is slow (backport #779)

cmd/cronosd/cmd/root.go
Solution:
- use DefaultBaseappOptions provided by sdk
=> Problem: new app options don't have affect

cmd/cronosd/cmd/root.go
Solution:
- use DefaultBaseappOptions provided by sdk
=> Problem: new app options don't has affect (backport #838)

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Solution:
- disable authz message in ante handler
=> Problem: authz is not used

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/test.yml
Solution:
- add event merge_group to the required workflows
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue
=> Problem: workflows are not ready for merge queue

.github/workflows/release.yml
Solution:
- update rocksdb version
=> Problem: windows build failed

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, integration_tests/test_filters.py
Closes: #856
Solution:
- cherry-pick the fix and integration test in ethermint
=> Problem: block hash returned in block filter is incorrect

integration_tests/poetry.lock, integration_tests/pyproject.toml, integration_tests/test_gravity.py, integration_tests/test_mempool.py
Solution:
- for the mempool test, retry it with flaky plugin
- try to make the gravity bridge test more stable
=> Problem: there are flaky integration tests

integration_tests/poetry.lock, integration_tests/pyproject.toml, integration_tests/test_gravity.py, integration_tests/test_mempool.py, nix/testenv.nix
Solution:
- for the mempool test, retry it with flaky plugin
- try to make the gravity bridge test more stable
=> Problem: there are flaky integration tests (backport #860)

versiondb/client/dump.go, versiondb/extsort/sort.go
=> Problem: error return of closing writable file is not checked (backport #858)

.gitignore, go.work
=> Problem: go.work is not ignore for develop use

integration_tests/test_versiondb.py
=> Problem: missing assert in balance check for versiondb test

integration_tests/test_versiondb.py
=> Problem: missing assert in balance check for versiondb test (backport #872)

app/ante/ante.go, app/app.go, app/test_helpers.go, x/cronos/handler.go, x/cronos/handler_test.go, x/cronos/keeper/ibc.go, x/cronos/keeper/keeper.go, x/cronos/keeper/msg_server.go, x/cronos/keeper/params.go, x/cronos/middleware/conversion_middleware.go, x/cronos/proposal_handler.go, x/cronos/simulation/operations.go, x/cronos/types/errors.go, x/cronos/types/messages.go
Solution:
- replace with `cosmossdk.io/errors`
=> Problem: sdkerrors.Wrap is deprecated

integration_tests/shell.nix, integration_tests/test_gravity.py, integration_tests/test_upgrade_gravity.py
Solution:
- skip gravity bridge test cases in v1.0.x branch.
=> Problem: hard to maintain gravity bridge tests in v1.0.x

CHANGELOG.md, cmd/cronosd/cmd/versiondb.go, cmd/cronosd/opendb/opendb_rocksdb.go, go.mod, go.sum, gomod2nix.toml, versiondb/client/flags.go, versiondb/client/ingest_sst.go, versiondb/client/restore_app_db.go, versiondb/go.mod, versiondb/go.sum
Solution:
- enable it on new db, but don't override existing db
- another implication is, user can manually modify the OPTIONS file to tune the options that's not set by app
=> Problem: dynamic-level-bytes is not enabled for restored application.db (backport: #904)

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Solution:
- apply a configurable limit in rpc nodes
=> Problem: eth_call return value is unlimited

cmd/cronosd/opendb/opendb_rocksdb.go
Solution:
- try to find options for default column family
=> Problem: loadLatestOptions don't find correct options

integration_tests/contracts/contracts/TestMessageCall.sol, integration_tests/test_basic.py, integration_tests/test_filters.py, integration_tests/test_subscribe.py
Updates: https://github.com/crypto-org-chain/cronos/issues/886
=> Problem: no subscribe log event test

.github/workflows/release.yml
Solution:
- fix the checksum files
=> Problem: release workflow fails at checksums

integration_tests/test_basic.py
=> Problem: cmd append with existing arguments in test_tx_inclusion

cmd/cronosd/opendb/opendb_rocksdb.go
Solution:
- try to find options for default column family
=> Problem: loadLatestOptions don't find correct options (backport: #910)

integration_tests/contracts/contracts/TestMessageCall.sol, integration_tests/test_basic.py, integration_tests/test_filters.py, integration_tests/test_subscribe.py, integration_tests/utils.py
=> Problem: no subscribe log event test (backport: #901)

memiavl/README.md
=> Problem: memiavl README is not up-to-date

.github/workflows/sims.yml
Closes: https://github.com/crypto-org-chain/cronos/issues/919
=> Problem: sim tests are fail due to invalid symmetric

default.nix, flake.nix, nix/default.nix, nix/rocksdb.nix
Solution:
- it's possible to support static build on linux with a few tweaks.
```
$ # native build on arm64
$ nix build github:yihuang/cronos/static-build#legacyPackages.aarch64-linux.pkgsStatic.cronos-matrix.cronosd
$ # cross-compile from arm64 to x86
$ nix build github:yihuang/cronos/static-build#legacyPackages.aarch64-linux.pkgsCross.gnu64.pkgsStatic.cronos-matrix.cronosd
```
=> Problem: static build on linux fails

CHANGELOG.md, default.nix, go.mod, go.sum, gomod2nix.toml
Solution:
- bump version number
- update changelog
=> Problem: v1.0.6 is not released

memiavl/benchmark_test.go, memiavl/snapshot.go, memiavl/snapshot_test.go, versiondb/client/flags.go, versiondb/client/verify.go
Solution:
- it don't have a clear use case right now and slow to build, make it optional.
=> Problem: memiavl hash index writing is not optional

scripts/release.sh
Solution:
- use static-linking in release script
=> Problem: released linux binaries don't use static linking

memiavl/benchmark_test.go, memiavl/changeset.go, memiavl/changeset_test.go, memiavl/snapshot_test.go, memiavl/tree.go, memiavl/tree_test.go, versiondb/client/verify.go
Solution:
- add basic change set APIs, prepare for the WAL support.
=> Problem: no changeset APIs in memiavl

memiavl/iterator.go, memiavl/iterator_test.go, memiavl/tree.go
Closes: #951
implement and test
=> Problem: memiavl iterator not implemented

.golangci.yml, memiavl/iterator_test.go
Solution:
- remove revive linter
- fix unit test failure
=> Problem: CI lint fails

CHANGELOG.md, app/app.go, integration_tests/cosmoscli.py, integration_tests/test_ibc_update_client.py
* add missing client route for ibc
* rm ibchost route
* add change doc
* add test_ibc_update_client
---------
=> Problem: no handler exists for proposal type when update-client (backport: #945)

x/cronos/keeper/evmhandlers/send_to_evm_chain.go
=> Problem: there is a typo in the evm chain handler

memiavl/changeset.go, memiavl/changeset_test.go, memiavl/iterator_test.go
=> Problem: memiavl changesets incorrectly unmarshal `KVPairs` with `.Delete = true`

x/cronos/keeper/evmhandlers_test.go
this change should have been included in 3f66f9e
=> Problem: there is a typo in the evm chain handler test

memiavl/changeset.pb.go, memiavl/db.go, memiavl/db_test.go, memiavl/go.mod, memiavl/multitree.go, proto/memiavl/changeset.proto
Solution:
- support store name upgrades
- include the upgrades in WAL record
=> Problem: memiavl don't support store upgrades

memiavl/db.go, memiavl/db_test.go
=> Problem: keep recent snapshots are not optional

CHANGELOG.md, default.nix
prepare changelog and version number
=> Problem: v1.0.7 is not released

memiavl/db_test.go, memiavl/tree_test.go
=> Problem: not cover cap case for init version test

integration_tests/cosmoscli.py, integration_tests/ibc_utils.py, integration_tests/test_basic.py, integration_tests/test_gov_update_params.py, integration_tests/test_gravity.py, integration_tests/test_ibc_update_client.py, integration_tests/test_upgrade.py, integration_tests/utils.py, nix/hermes.nix, nix/sources.json
=> Problem: ibc update client state change is not covered

memiavl/go.mod, memiavl/mem_node.go, memiavl/node.go, memiavl/persisted_node.go, memiavl/proof.go, memiavl/proof_test.go, memiavl/tree.go, memiavl/tree_test.go
Closes: #976 
Solution:
- add the implementaion, some part if ported from iavl library
=> Problem: memiavl don't support ics23 merkle proof generation

integration_tests/test_versiondb.py, memiavl/multitree.go, memiavl/tree.go, versiondb/client/verify.go
Solution:
- adapt versiondb integration test to memiavl and re-enable it.
=> Problem: versiondb integration test is skipped

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/lint.yml, .github/workflows/sims.yml, CHANGELOG.md, default.nix, flake.nix, go.mod, nix/default.nix, versiondb/go.mod
Solution:
- update go version, prepare for memiavl integration
=> Problem: go1.20 is not used

integration_tests/cosmoscli.py, integration_tests/test_ibc_update_client.py
=> Problem: ibc update client via chain header is not covered by test

versiondb/client/verify.go
Solution:
- ignore the store when binary registered more stores then the change sets
=> Problem: changeset  verify fail for non-exist stores

memiavl/layout_little_endian.go, memiavl/layout_native.go, memiavl/persisted_node.go
=> Problem: NodeLayout has unnesserary bound check

memiavl/benchmark_test.go, store/rootmulti/store.go
Solution:
- add the support
- add more lru cache implementations to the benchmark
=> Problem: memiavl store don't support inter-block cache

.github/workflows/build.yml, .github/workflows/linkchecker.yml, .github/workflows/lint.yml, .github/workflows/test.yml, app/app.go, app/export_test.go, app/test_helpers.go, memiavl/benchmark_test.go, memiavl/snapshot_test.go, x/cronos/handler_test.go, x/cronos/keeper/keeper_test.go
=> Problem: keeper test fail due to skip gravity

.github/workflows/build.yml, .github/workflows/lint.yml, Makefile, app/app.go, go.mod, go.sum, gomod2nix.toml, versiondb/go.mod, versiondb/go.sum
Solution:
- update dependency, this version works with cronos mainnet statesync, very fast restoration.
=> Problem: latest memiavl fixes not updated

app/app.go, go.mod, go.sum, gomod2nix.toml
Solution:
- integrate recent [async-wal optimization](https://github.com/crypto-org-chain/cronos/pull/1004), it's very fast for catching-up the chain
=> Problem: async-wal is not integrated to v1.0.x

integration_tests/gravity_utils.py, integration_tests/network.py, integration_tests/test_gravity.py, integration_tests/test_gravity_2.py, integration_tests/test_ibc.py, integration_tests/utils.py
=> Problem: gravity related tests are not easy to reuse

default.nix, flake.lock, flake.nix, nix/build_overlay.nix, nix/default.nix, nix/sources.json
Solution:
- update nixpkgs and go src
=> Problem: go 1.20.3 is not used

nix/sources.json
=> Problem: fix cross compilation of zstd on darwin is not included

nix/build_overlay.nix, nix/playtests-darwin.patch, nix/zstd.nix
Solution:
- fix the zstd nix expression
=> Problem: macos cross compiling failed

app/app.go, integration_tests/configs/default.jsonnet, memiavl/benchmark_test.go, memiavl/db.go, memiavl/db_test.go, memiavl/export.go, memiavl/iterator.go, memiavl/mmap.go, memiavl/multitree.go, memiavl/proof_test.go, memiavl/snapshot.go, memiavl/snapshot_test.go, memiavl/tree.go, memiavl/tree_test.go, store/rootmulti/store.go, versiondb/client/restore_app_db.go, versiondb/client/verify.go
Closes: #1009
- make the default behavior safe
- provide the unsafe zero-copy option
=> Problem: memiavl's memory copy behavior is not consistent

memiavl/db.go, memiavl/export.go, memiavl/persisted_node.go, memiavl/snapshot.go, memiavl/snapshot_test.go, memiavl/tree.go, store/rootmulti/store.go
Solution:
- support all versions, but still support the efficient algorithm if the target version happens to be the snapshot version
=> Problem: memiavl export only support snapshot height

memiavl/db.go, memiavl/db_test.go, memiavl/import.go
Solution:
- make snapshot taking and pruning working on temporary directory, assume atomicity of directory rename operation.
=> Problem: memiavl snapshot and pruning leave corrupted snapshot

nix/build_overlay.nix
=> Problem: go 1.20.4 is not used (backport #1046)

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, memiavl/go.mod, memiavl/go.sum, store/go.mod, store/go.sum, versiondb/go.mod, versiondb/go.sum
=> Problem: cometbft dependency is not updated

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, versiondb/go.mod, versiondb/go.sum
* Problem: cometbft dependency is not updated
* add change log
=> Problem: cometbft dependency is not updated (backport: #1062)

app/app.go, client/docs/embed.go, client/docs/statik/init.go, go.mod, scripts/protoc-swagger-gen.sh, scripts/update-swagger-ui-statik.sh
=> Problem: statik bring big binary size diff

app/app.go, go.mod, go.sum, gomod2nix.toml
- update memiavl dependency
- fix graceful shutdown when replaying local bocks
- make halt-height deterministic, useful to keep memiavl and versiondb in sync.
=> Problem: latest memiavl is not integrated

CHANGELOG.md, default.nix
Solution:
- turn on it by default, it only works for little-endian machines, which is most of them anyway.
- it'll panic on big-endian machine, who needs to build custom binary for themselves.
=> Problem: the nativebyteorder is not turned on by default

CHANGELOG.md, memiavl/db.go, memiavl/multitree.go, store/rootmulti/store.go, store/rootmulti/store_test.go
Solution:
- support the use case used by x/upgrade
=> Problem: LastCommitID crashes when memiavl is not loaded first

app/app.go, go.mod, go.sum, gomod2nix.toml
Solution:
- update memiavl deps to fix wal replay bug
=> Problem: latest memiavl not integrated

memiavl/db.go, memiavl/db_test.go
Solution:
- only do in write mode
=> Problem: memiavl tmp dir removal in read-only mode

.github/workflows/build.yml, .github/workflows/lint.yml, CHANGELOG.md, go.mod, integration_tests/test_gravity.py, integration_tests/test_ibc.py, x/cronos/keeper/gravity_hooks.go, x/cronos/keeper/keeper.go
* avoid emit duplicate events
for more info, see https://github.com/cosmos/cosmos-sdk/pull/13063/files
* test dup in ibc
* add change doc
* test dup in gravity
* pin nixpkgs flake
* pin to local nixpkgs
* pin to 23.05
* fix unit test
---------
=> Problem: duplicate cache events are emitted (backport #1102)

app/app.go
=> Problem: duplicate streamers are loaded

memiavl/db.go
=> Problem: duplicate MkdirAll are called when rewrite snapshot

.github/workflows/build.yml, .github/workflows/lint.yml, CHANGELOG.md, cmd/cronosd/opendb/opendb_rocksdb.go, go.mod, go.sum, gomod2nix.toml, nix/rocksdb.nix, versiondb/go.mod, versiondb/go.sum, versiondb/tsrocksdb/opts.go
* Problem: rocksdb 8.0 is not used
Solution:
- fix build issue in grocksdb
- update dependencies
- enable OptimizeFiltersForMemory
* fix resolve
* rocksdb 8.1.1
* fix resolve
* changelog
* install golangci-lint separately
* fix workflow
* fix deps
* fix unittest workflow
* fix workflow
* fix unittest workflow
---------
=> Problem: rocksdb 8.0 is not used (backport #940)

CHANGELOG.md, versiondb/client/flags.go, versiondb/client/restore_app_db.go
Solution:
- introduce "--sdk46-compact" flag to support both.
=> Problem: versiondb commands not compatible with sdk 47

default.nix
=> Problem: librocksdb version is not updated

integration_tests/test_upgrade.py
wait one block to avoid invalid chain id for signer
=> Problem: deploy contract is flaky in upgrade test

default.nix, nix/rocksdb.nix
=> Problem: librocksdb has wrong rpath in cross-compiling (backport: #1131, #1126)

x/cronos/keeper/keeper_test.go, x/cronos/keeper/mock/ibckeeper_mock.go
For more [info](https://github.com/golangci/golangci-lint/releases/tag/v1.54.2)
=> Problem: golangci-lint fail at v1.54.2 on github action

memiavl/db.go
Solution:
- Batch wal writing when there are queue-ed commit buffer, it helps a lot in fast commit benchmark, might has positive impact in catching-up phase when blocks are small.
=> Problem: memiavl wal writing is not batched

integration_tests/test_ibc.py
=> Problem: there is a typo in the comment for ibc integration test

integration_tests/cosmoscli.py, integration_tests/test_upgrade.py, integration_tests/test_upgrade_gravity.py, integration_tests/utils.py
=> Problem: start with exported genesis is not tested (backport #1140)

x/icaauth/client/cli/tx_register_account.go
this change should have been included in 265459d6e22897f3065e69bd6d453eda06fb1be7
=> Problem: miss version flag when register ica account

memiavl/benchmark_test.go, memiavl/go.mod, memiavl/go.sum, memiavl/tree.go
Solution:
- make the cache optional
- cleanup the benchmark
without cache: 152.0ns, cache hit: 11.51ns, cache miss 319.1ns, the question is, how useful is the cache in this case?
cache miss adds too much overhead compared to the no-cache version.
=> Problem: memiavl performance regression when cache miss

app/bench_test.go
Solution:
- fix it
BTW, there seems to be some performance regression.
=> Problem: erc20 benchmarking fails

go.mod, go.sum, gomod2nix.toml, integration_tests/test_basic.py
Solution:
- integration latest ethermint
=> Problem: statedb balance is not handled consistently

integration_tests/contracts/contracts/TestICA.sol, integration_tests/ibc_utils.py, integration_tests/test_ica_precompile.py
=> Problem: ica timeout is not tested

.github/workflows/test.yml
=> Problem: integration test workflow fails if no code changes

CHANGELOG.md, app/app.go, integration_tests/test_bank_precompiles.py
=> Problem: bank precompile is not ready to release

nix/rocksdb.nix
- handle the major version dynamically.
=> Problem: rocksdb nix expression hard code the major version

integration_tests/ibc_utils.py
Solution:
- handle exception properly
The gist of it is try not to manually drive generators, can easily miss the exception handling part.
=> Problem: ibc integration test setup failure don't close supervisord

integration_tests/configs/cosmovisor.jsonnet, integration_tests/cosmoscli.py, integration_tests/test_basic.py, integration_tests/test_upgrade.py, integration_tests/utils.py
=> Problem: update send_enable params in proposal is not tested

CHANGELOG.md
=> Problem: v1.1.0-rc1 is not released

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, nix/rocksdb.nix
see: https://github.com/facebook/rocksdb/issues/11945
Solution:
- postpone the upgrade
=> Problem: new rocksdb need manual flush to upgrade

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, x/cronos/rpc/api.go
* Problem: websocket refactoring not used
Solution:
- use the recent websocket/filter system refactoring in ethermint.
* update ethermint
* update filter offset to latest so only new changes are fetched in next call
* fix filter
* Revert "update filter offset to latest so only new changes are fetched in next call"
This reverts commit 6910f84d40ef0113f730533e83fe9a010faee82c.
* changelog
---------
=> Problem: websocket refactoring not used (backport #1239)

CHANGELOG.md, default.nix
- Refactor websocket/subscription system to improve performance and stability of subscription and filtering system in websocket and json-rpc.
- Tune rocksdb options to drop memory consumption.
- Greatly improve memiavl state sync restore speed by 2x.
=> Problem: v1.0.13 is not released

CHANGELOG.md, app/app.go, app/forks.go
=> Problem: need hardfork to adjust feemarket parameters

app/forks.go
=> Problem: min-gas-price decimals is wrong

CHANGELOG.md, default.nix
=> Problem: base fee hardfork is not released

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Solution:
- fix in ethermint, update deps
=> Problem: filter timeout cause nil pointer panic

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
=> Problem: no int64 check in error msg

.github/workflows/test.yml, Makefile, integration_tests/conftest.py, integration_tests/test_exported_genesis.py, integration_tests/test_ibc.py, integration_tests/test_ibc_timeout.py, integration_tests/test_ibc_update_client.py, integration_tests/test_mempool.py, integration_tests/test_pruned_node.py, integration_tests/test_replay_block.py, integration_tests/test_upgrade.py, scripts/run-integration-tests
* Problem: integration tests CI spend a lot of time
Solution:
- run in parallel using markers and job matrix
* fix matrix
* flock is not nesserary
* fix marker
* break up ibc test cases
* separate gov test cases
* split out some slow test cases
* split more ibc test
* Update .github/workflows/test.yml
* fix pytest lint
* more balance
---------
=> Problem: integration tests CI spend a lot of time (backport #1271)

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
=> Problem: sdk v0.46.x is outdated

CHANGELOG.md, app/app.go, go.mod, store/memiavlstore/store.go, store/rootmulti/store.go, versiondb/tsrocksdb/store.go, x/cronos/keeper/mock/ibckeeper_mock.go
=> Problem: versiondb version mismatch related fixes are not backported

go.mod, store/go.mod, versiondb/go.mod
=> Problem: internal dependencies not updated

.github/workflows/build.yml, CHANGELOG.md, app/app.go, versiondb/multistore.go, versiondb/tsrocksdb/store.go, versiondb/types.go
Solution:
- flush the wal before quit the node, make the rocksdb upgrade smooth.
Update CHANGELOG.md
fix flush
=> Problem: rocksdb wal format sometimes not backward compatible (backport #1379)

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, integration_tests/test_upgrade.py
=> Problem: panic on invalid elasticity_multiplier (backport #1397)

CHANGELOG.md, default.nix
=> Problem: v1.2.2 not released

.github/workflows/release.yml, CHANGELOG.md, default.nix, go.mod, go.sum, gomod2nix.toml, integration_tests/configs/cosmovisor.jsonnet, integration_tests/configs/upgrade-test-package.nix, integration_tests/cosmoscli.py, integration_tests/test_upgrade.py, integration_tests/utils.py, x/cronos/rpc/api.go
=> Problem: v1.2.x changes not sync to v1.3.x

app/upgrades.go
=> Problem: contract migration in upgrade

app/app.go, app/proposal.go
Solution:
- add unsafe option to unblock the case.
=> Problem: validator unable to start up

CHANGELOG.md, app/app.go, go.mod, go.sum, gomod2nix.toml, integration_tests/test_e2ee.py, integration_tests/test_mempool.py
=> Problem: pending tx comes after get mined

CHANGELOG.md, app/app.go, go.mod, go.sum, gomod2nix.toml
=> Problem: decode tx is unnecessary in tx listener (backport: #1467)

app/upgrades.go
=> Problem: mainnet migration not provided

x/cronos/types/messages.go
Solution:
- implements legacytx.LegacyMsg
=> Problem: internal msg can't be used in amino sign

CHANGELOG.md, x/cronos/keeper/precompiles/relayer.go
…rChainIsSource (#1458)"
This reverts commit 0ef63b927ff49ca7131416606df6c540aa34486b.
=> Revert "Problem: require gas in RecvPacket is inaccurate when ReceiverChainIsSource

CHANGELOG.md, versiondb/tsrocksdb/store.go
=> Problem: memory leak in versiondb (backport: #1491)

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
=> Problem: cometbft not up to date

CHANGELOG.md, versiondb/tsrocksdb/iterator.go
=> Problem: redundant copy in check validate (back port: #1498)

CHANGELOG.md, integration_tests/cosmoscli.py, integration_tests/test_e2ee.py, x/e2ee/client/cli/cmd.go, x/e2ee/client/cli/pubkey.go
=> Problem: no command to show current pubkey in e2ee

CHANGELOG.md, cmd/cronosd/opendb/opendb_rocksdb.go
=> Problem: pinL0FilterAndIndexBlocksInCache is not enabled (backport #1529) 

CHANGELOG.md, app/app.go
Solution:
- respect the max-txs config as sdk
changelog
=> Problem: sdk mempool can't be disabled

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
=> Problem: hash in subscribe newHeads differs from eth_getBlockByNumber

testground/benchmark/benchmark/peer.py, testground/benchmark/benchmark/stateless.py
Solution:
- use validator leader node to generate genesis, so we can set zero fullndoes
=> Problem: benchmark don't support validator only

CHANGELOG.md, default.nix
=> Problem: v1.3.2 is not released

.github/workflows/container.yml
Solution:
- port the github workflow
=> Problem: v1.3.x testground image not uploaded

testground/README.md, testground/benchmark/benchmark/stateless.py
allow wait longer when timeout_commit is small
=> Problem: number of idle_blocks is not configurable (backport #1631)

.gitignore, go.mod, go.sum, gomod2nix.toml, nix/testground-cronosd.patch, nix/testground-image.nix
=> Problem: no way to disable nonce checking in benchmark

CHANGELOG.md, default.nix
=> Problem: v1.3.3 is not released

.github/workflows/lint.yml, Makefile, default.nix, flake.nix, integration_tests/configs/broken-cronosd.nix, integration_tests/configs/upgrade-test-package.nix, integration_tests/shell.nix, nix/bundle-win-exe.nix, nix/cosmovisor.nix, nix/cronos-matrix.nix, nix/dapptools-overlay.nix, nix/default.nix, nix/gen-binding-shell.nix, nix/go-ethereum.nix, nix/golangci-lint.nix, nix/hermes.nix, nix/rocksdb.nix, nix/scripts.nix, nix/sources.nix, nix/testenv.nix, nix/testground-image.nix, testground/benchmark/flake.nix, testground/benchmark/overlay.nix
Solution:
- switch to nixfmt-rfc-style
=> Problem: nixpkgs-fmt is deprecated

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, integration_tests/test_basic.py
=> Problem: no trace detail on insufficient balance fix is not included (backport #1679)

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
Include json-rpc bug fixes, and fix versiondb corrupted data.
[CHANGELOGS]()
1. Stop node, upgrade binary to `v1.3.4`.
2. Run `cronosd changeset fixdata /path/to/node/data/versiondb`, takes a few minutes.
3. Start the node with binary `v1.3.4`.
=> Problem: v1.3.4 is not released

CHANGELOG.md
v1.4.0-rc4 is not non-consensus-breaking upgrade against rc3, it enables async-pruning feature in iavl v1 to fix the node hanging issue we faced when upgrade testnet, also includes a versiondb tool to fix a data corruption issue.
=> Problem: v1.4.0-rc4 is not released

CHANGELOG.md, default.nix
`v1.4.1` fixes 2 RPC issues, it's highly recommended for node operators to use this version to the v1.4 mainnet upgrade.
=> Problem: v1.4.1 is not released

CHANGELOG.md, default.nix, go.mod, go.sum, gomod2nix.toml, nix/testenv.nix
=> Problem: ibc-go is not up to date

.github/workflows/sims.yml, CHANGELOG.md, app/app.go, app/storeloader.go, app/upgrades.go, integration_tests/shell.nix, integration_tests/test_versiondb.py, memiavl/db.go, memiavl/db_test.go
* Problem: version mismatch happen occationally
Solution:
- make sure don't load iavl version ahead of versiondb
* changelog
* Update app/app.go
* memiavl support write old version idopodently
* add unit test
* fix upgrade store loader
* reproduce in integration test
* fix memiavl
* better test
* fix lint
---------
=> Problem: version mismatch happen occasionally (backport #1759)

CHANGELOG.md, integration_tests/configs/default.jsonnet, memiavl/multitree.go
When consolidate minimal version between memiavl and versiondb, we expect memiavl to load up to the target version, rather than exact target version.
Update CHANGELOG.md
=> Problem: memiavl too strict on target version (backport #1780)

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml
=> Problem: eth_getLogs miss logs with batch transactions

testground/benchmark/flake.nix, testground/benchmark/overlay.nix
=> Problem: testground image build fail

CHANGELOG.md, go.mod, go.sum, gomod2nix.toml, integration_tests/test_basic.py, integration_tests/utils.py
=> feat: add support for eth_getBlockReceipts

CHANGELOG.md, default.nix, docs/api/json-rpc/endpoints.md, docs/api/json-rpc/events.md, docs/api/json-rpc/server.md, docs/architecture/adr-001.md, docs/architecture/adr-008.md
=> release: v1.4.8

go.mod, go.sum
=> fix(grpc): add sanity check to trace_tx follow up

CHANGELOG.md, default.nix, gomod2nix.toml
=> release: v1.4.9

.github/workflows/build.yml, .github/workflows/container.yml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/sims.yml, .github/workflows/test.yml, integration_tests/test_basic.py, memiavl/multitree.go
chain-main uses memIAVL, store, and versionDB. It has an issue as described in cosmos/cosmos-sdk#14916, so we need to apply a hacky solution to it.
=> fix: chain-main upgrade cosmos-sdk v0.50 mismatch apphash
